### ISSUE TITLE
modification de mise en forme quand on change de niveau de zoom

### ISSUE THREAD

**Issue by EliCommins** [davidonet/Textopoly#10]
Sur la version alpha (assez différente de la dev au moment où ces lignes sont écrites): au 3e niveau de zoom, j'écris en majuscules "JULIEN D." dans une case longue. "JULIEN D." est placé sur une seule ligne.
Quand je dézoome au niveau 4, le "D." vient se placer sur la ligne du dessous par rapport au "JULIEN". L'ensemble est donc placé sur deux lignes et ma mise en forme d'origine a été modifiée.
Si on peut éviter, c'est mieux, question de logique à l'écriture.

**Comment by davidonet** [comment]
Je pense que ce bug est résolu sur la version en cours...
