### ISSUE TITLE
problème d'accès à la page chemin

### ISSUE THREAD

**Issue by EliCommins** [davidonet/Textopoly#101]
en partant de la page http://textopoly.org/mpath/Eli

et en cliquant sur mon chemin (en bas)

j'obtiens une page d'erreur

http://textopoly.org/mbook/5076a8f4b40a5c9e150000fd

**Comment by davidonet** [comment]
Les url  http://textopoly.org/m... ne sont pas utilisables
http://textopoly.org/admin/user/Eli
