### ISSUE TITLE
saisie à l'aveugle en mode explorer / bouton édition

### ISSUE THREAD

**Issue by EliCommins** [davidonet/Textopoly#102]
- mode explorer
- case -55, 35, bouton éditer
- j'écris à la volée puis arrive à la limite de la boîte
- je continue et je dois saisir environ 6 ou 7 caractères avant que la mise en forme ne bascule dans la feuille de style suivante
- je me retrouve donc dans une situation où je dois saisir des caractères à l'aveugle, avant le basculement.

**Comment by davidonet** [comment]
Duplicate #102
