### ISSUE TITLE
Pas de chemins sous Explorer 9

### ISSUE THREAD

**Issue by EliCommins** [davidonet/Textopoly#11]
Les chemins de lecture n'apparaissent pas sous Explorer 9

**Comment by davidonet** [comment]
Oui je viens de faire des tests effectivement ça marche pas non plus avec firefox :-( sous windows. J'ai l'impression que c'est un problème de transparence de couches. Je vais essayer d'écrire un test spécifique pour comprende ce qu'il se passe.

Bug confirmé sur 
IE9 / Windows7
FF4 / Windows7 
FF15 / Linux

**Comment by davidonet** [comment]
Corrigé sur http://dev.textopoly.org
Vérifié sur : 
FF15 / Linux
IE9 / Windows 7
FF4 / Windows 7
