### ISSUE TITLE
Les utilisateurs non enregistrés arrivent sur le mode d'emploi

### ISSUE THREAD

**Issue by zakxxi** [davidonet/Textopoly#113]
-6,-28 sur textopoly.org

**Comment by davidonet** [comment]
C'est le cas non ?

**Comment by EliCommins** [comment]
Sur la case où c'est écrit "mode d'emploi", pas sur le point d'interrogation. Pas le cas à ma connaissance.

(Envoyé depuis un téléphone)

**Comment by davidonet** [comment]
Quand j'ouvre http://textopoly.org avec un navigateur en mode incognito (sans cookie, ni authentification) : la case Mode d'emploi est au centre de l'écran. C'est pas ça qu'on veut ? cf #95

**Comment by zakxxi** [comment]
effectivement c'est bon ;-)
