### ISSUE TITLE
Réglage du zoom

### ISSUE THREAD

**Issue by EliCommins** [davidonet/Textopoly#13]
Le niveau de zoom n'est pas ajusté correctement en fonction du mode choisi (sous Explorer 9 en tout cas)

**Comment by davidonet** [comment]
Avec les autres navigateurs, le comportement est il celui attendu ?

**Comment by EliCommins** [comment]
oui, sur mon PC Mairie, le comportement est le même sous Explorer et
Firefox. pour l'instant, je n'arrive pas à avoir les autorisations pour
installer Chrome.

**Comment by davidonet** [comment]
Firefox sous Linux marche par non plus :-(
ça doit être pareil avex Firefox OSX...

**Comment by zakxxi** [comment]
Le 18 sept. 2012 à 12:06, David Olivari a écrit :

> Firefox sous Linux marche par non plus :-(
> ça doit être pareil avex Firefox OSX...

je confirme…

> —
> Reply to this email directly or view it on GitHub.
- \+ +
  Adrien Revel
- \+ +
  adrien@startxxi.eu
  mob : +33 645 247 971
  tél/fax : +33 953 341 541
  skype : zakxxi
- \+ +

**Comment by davidonet** [comment]
Erreur sur le suivi de bugs, Les commentaires concernaient la visu des chemins.

Le changement de zoom (affichage et curseur) lorsque l'on clique sur ecrire fonctionne sur :
Firefox15 / Linux
IE9 / Windows 7
Firefox4 / / Windows 7
