### ISSUE TITLE
en mode écrire, afficher un curseur de la taille d'une cellule de base

### ISSUE THREAD

**Issue by davidonet** [davidonet/Textopoly#23]

**Comment by EliCommins** [comment]
pas de curseur "écrire" sous PC/Firefox (il garde la flèche)
ok sous Explorer

**Comment by zakxxi** [comment]
chez moi (firefox 15 windows 7) pas de bug

**Comment by davidonet** [comment]
Sous Linux : 
Fonctionne avec firefox mais pas avec chrome

**Comment by davidonet** [comment]
Ce n'est pas le bon bug.
Celui ci concernait le curseur de grande taille qui permet de voir la grille sous jacente
