### ISSUE TITLE
Mode mobile

### ISSUE THREAD

**Issue by davidonet** [davidonet/Textopoly#26]
Avoir un mode mobile minimum.

**Comment by davidonet** [comment]
Le mode mobile est activé automatiquement par le user agent à la connection sur le site.

**Comment by davidonet** [comment]
Les billets sont interactifs si on les touche on affiche leur lecture à plat

**Comment by davidonet** [comment]
Navigation de la carte au billet par lien réciproque
http://dev.textopoly.org

**Comment by EliCommins** [comment]
comprends pas

**Comment by davidonet** [comment]
On peut passer de la carte à la vue billet en cliquant dessus et revenir à la carte en cliquant sur les coordoonnées en vue billet

**Comment by davidonet** [comment]
en mode mobile tout ça...

**Comment by EliCommins** [comment]
ok

**Comment by EliCommins** [comment]
super tes idées pour le site mobile, tout le monde est très content ici
