### ISSUE TITLE
S'authentifier par un réseau social

### ISSUE THREAD

**Issue by davidonet** [davidonet/Textopoly#27]
Concernant la connexion au réseau sociaux et le post via facebook, on ne pourra techniquement le mettre en place que lorsque le site aura trouvé son hébergeur final.

Il faut effet identifier le site qui souhaite se connecter à facebook ou twitter par son url. 
Je me concentre donc en attendant sur une solution d'authentification Textopoly.

**Comment by EliCommins** [comment]
ok

2012/9/24 David Olivari notifications@github.com

**Comment by davidonet** [comment]
won't fix : #124
