### ISSUE TITLE
ajout du nom et choix de la couleur pour une 1ère utilisation

### ISSUE THREAD

**Issue by EliCommins** [davidonet/Textopoly#29]
une utilisatrice a bloqué sur la boîte d'ajout du nom et de la couleur, car elle n'a pas vu qu'il fallait inscrire un nom en plus de choisir la couleur. une bulle d'avertissement serait la bienvenue pour signaler qu'il faut saisir un nom avant de poursuivre

**Comment by davidonet** [comment]
Le comportement d'authentification va changer : 
La demande d'authentification si l'on ne s'est pas volontairement identifier va se faire au moment où l'on clique que le bouton "écrire" ou "chemin"
