### ISSUE TITLE
Sur le site mobile, les images sont trop volumineuses

### ISSUE THREAD

**Issue by davidonet** [davidonet/Textopoly#30]
Le chargement d'une page est trop long en 3G.
Je vais générer des vignettes pour la carte, l'image en grande taille sera visible en cliquant dessus.

**Comment by davidonet** [comment]
La page mobile tout compris pèse moins de 100ko avec les images réduites à 192x128

**Comment by EliCommins** [comment]
Bcp plus rapide, je textopolise dans le tram sans problème

(Envoyé depuis un téléphone)
