### ISSUE TITLE
Plusieurs problèmes en mode tracer un chemin

### ISSUE THREAD

**Issue by EliCommins** [davidonet/Textopoly#37]
- le bouton "valider le chemin" ne semble pas fonctionner correctement: il faut que je valide sur une case suivante pour que le chemin s'affiche
- parfois le chemin choisi reste en jaune après validation et on ne sait donc pas si la validation a bien été prise en compte
- à mon avis, il faut prévoir un bouton "annuler ce chemin" et/ou "retirer cette case du chemin", car on peut facilement faire un erreur d'ajout quand on crée un chemin
- quand deux chemins se croisent, on ne peut pas les distinguer et donc pas toujours les suivre

**Comment by EliCommins** [comment]
on peut imaginer la solution suivante pour clarifier : sur la première case du futur chemin, il n'y a que le bouton "+". A partir de la 2e case, une fois qu'on clique sur le "+", le bouton "valider" apparaît, et ainsi de suite. ceci pour éviter d'appuyer sur "valider" avant de passer par le "+".

**Comment by davidonet** [comment]
duplicate #51
duplicate #52
duplicate #53
duplicate #54
duplicate #55
