### ISSUE TITLE
en mode écrire, afficher une boîte vide pour figurer les cases libres pour l'écriture?

### ISSUE THREAD

**Issue by EliCommins** [davidonet/Textopoly#41]

**Comment by davidonet** [comment]
C'est plus un curseur de la taille d'une case de base. 
On en peut pas connaitre l'état de réservation sans interroger le serveur.

La réservation est gérée de la façon suivante : 
- on clique sur une case
- le navigateur fait une requête au serveur pour connaître l'état de réservation
- si elle est libre la case est réservé et  apparaît la boite de saisie
- si elle est occupée rien ne se passe et l'utilisateur clique ailleurs

**Comment by davidonet** [comment]
Fonction abandonnée
