### ISSUE TITLE
Problème d'envoi d'image

### ISSUE THREAD

**Issue by EliCommins** [davidonet/Textopoly#43]
En mode écrire, quand je clique sur le bouton "ajouter une image", puis sur "envoyer une image", rien ne se passe

**Comment by davidonet** [comment]
Le drag and drop fonctionne, mais le bouton n'est pas accessible.
J'ai fait un test un ajoutant à la main un <input type="file">Test</input> et ça marche pas non plus :-(
Je continue de chercher*

**Comment by davidonet** [comment]
On bloque le click dans la boite pour éviter le déplacement de la boite :- donc le bouton en dessous ne reçoit pas l"événement grrrr (3h là dessus)

**Comment by EliCommins** [comment]
ok reçu, bien joué.
