### ISSUE TITLE
Annulation d'un chemin

### ISSUE THREAD

**Issue by davidonet** [davidonet/Textopoly#53]
à mon avis, il faut prévoir un bouton "annuler ce chemin" et/ou "retirer cette case du chemin", car on peut facilement faire un erreur d'ajout quand on crée un chemin

**Comment by davidonet** [comment]
On va faire annuler le chemin dans un premier temps.
Pour ce qui est de supprimer, une case se sera plus facile de l'envisager sur la vue à plat

**Comment by zakxxi** [comment]
j'ai rajouté un bouton annuler mon chemin sur la pathBox
