### ISSUE TITLE
Ecrire une charte d'utlisation.

### ISSUE THREAD

**Issue by davidonet** [davidonet/Textopoly#73]
- Protection du droit d'auteur : texte et image
- Pas de garanti sur la pérennité des données postées
- Droit d'édition, suppresion, bannissement de la part de l'opérateur
- Information sur le stockage d'informations personnelles

**Comment by davidonet** [comment]
Quid de la traçabilté des utilisateurs ?

**Comment by EliCommins** [comment]
existe-t-il une solution? je pense qu'on peut laisser tomber l'idée de devoir retracer tous les utilisateurs, à moins d'un moyen simple de le faire. la charte devrait nous protéger, surtout si nous disposons d'un mail de l'utilisateur qui permet de renvoyer vers un opérateur. je me trompe?

**Comment by davidonet** [comment]
Je pense que légalement c'est plus sur de tracer les ip's de connexion. Tous les sites tracent les ip à des fins statistiques. On peut facilement utiliser un service externe : http://getclicky.com/ qui s'occupe de tout et nous fourni de beau graphique de stats 

Et puis, j'ai vu plein de films américain où ils sauvent le monde grâce à une adresse IP, ce serait dommage de pas sauver le monde, non ?

**Comment by EliCommins** [comment]
ok. et toujours ok pour sauver le monde.

**Comment by davidonet** [comment]
Pour info, Les sites vitrines purement institutionnels, non commmerciaux sont dispensés de déclaration à la condition qu’ils soient conformes à la dispense n° 7  :
http://www.cnil.fr/en-savoir-plus/deliberations/deliberation/delib/107/

**Comment by EliCommins** [comment]
merci pour cette bonne nouvelle.
