### ISSUE TITLE
gestion du nombre de caractères dans la case

### ISSUE THREAD

**Issue by EliCommins** [davidonet/Textopoly#79]
ma saisie n'est pas prise en compte dans la case au-delà d'un certain nombre de caractères. je n'ai pas de retour pour savoir si la limite est atteinte ou non.
sur textopoly.org, coordonnées -3, -33

**Comment by davidonet** [comment]
En effet, le nombre de caractère maximal est 600.
La limite est atteinte quand on ne peut plus écrire, non ?

**Comment by EliCommins** [comment]
oui, quand je teste maintenant c'est bon. plus tôt, je me suis trouvé dans
une situation où le texte débordait, mais je n'arrive pas à la reproduire.

je vais bientôt poster sur le github une série de notifications qui
devraient a priori plutôt concerner Adrien.

**Comment by EliCommins** [comment]
au milieu des questions pour Adrien, j'ai posté un billet sur les
permaliens affichés sur les fiches d'infos, qui ne marchent pas et semblent
renvoyer vers la version dev

2012/10/11 Eli Commins eli.commins@gmail.com

> oui, quand je teste maintenant c'est bon. plus tôt, je me suis trouvé dans
> une situation où le texte débordait, mais je n'arrive pas à la reproduire.
> 
> je vais bientôt poster sur le github une série de notifications qui
> devraient a priori plutôt concerner Adrien.
>
