### ISSUE TITLE
problème avec la touche "retour" en mode écriture

### ISSUE THREAD

**Issue by EliCommins** [davidonet/Textopoly#80]
je n'arrive pas à passer à la ligne en mode écriture à plusieurs reprises. par contre, parfois, ça marche.

en revenant pour éditer la case, elle affiche le texte copié et collé sur la case précédente. 

je recolle le bon texte : ce coup-ci, le "retour" fonctionne.

coordonnées 13, -35

**Comment by davidonet** [comment]
La transformation des retours à la ligne en espace ne sont pas implémentés dans la boite d'édition

**Comment by davidonet** [comment]
Duplicate #96
