### ISSUE TITLE
comportement étrange lié au geste copier / coller

### ISSUE THREAD

**Issue by EliCommins** [davidonet/Textopoly#81]
quand je me rends sur une case pleine pour l'éditer (mode explorer / sélection de case / bouton éditer), la boîte d'écriture s'ouvre sur un texte affiché qui n'est pas toujours celui  de la boîte elle-même, mais est celui issu d'un copier / coller précédent.
le texte placé en mémoire semble se replacer à ce moment-là.
ce n'est pas bloquant, car il suffit de l'effacer, mais j'ai l'impression que c'est lié aux autres problèmes cités en #80 et #79: quand j'observe ce comportement, j'ai visiblement du mal à utiliser la touche "retour", par exemple.

**Comment by davidonet** [comment]
Ok confirmé.
Si l'on change de case sans avoir validé l'édition en cours ou annuler : le texte est conservé. 
On risque d'écraser le texte en dessous

**Comment by davidonet** [comment]
Duplicate #96
