### ISSUE TITLE
Billet buggé en -4, -30

### ISSUE THREAD

**Issue by EliCommins** [davidonet/Textopoly#83]
le billet indique le nom de l'auteur ("Eli") alors qu'il est validé depuis longtemps. pas d'accès à la case d'infos.

**Comment by davidonet** [comment]
C'est un billet vide, il ne devrait pas être dans la base. Je vérifie le code qui gère ça
(Je l'ai supprimé en attendant)

**Comment by davidonet** [comment]
duplicate #96
