### ISSUE TITLE
problème d'affichage?

### ISSUE THREAD

**Issue by EliCommins** [davidonet/Textopoly#9]
ceci m'arrive parfois :
- je zoome sur une zone donnée
- à ce niveau de zoom, je fais glisser la carte dans un sens (par exemple, vers la droite)
- les caractères à gauche (vers là où je vais) ne s'affichent pas, alors qu'ils sont là à un niveau de zoom différent et qu'ils ont bien été enregistrés

**Comment by davidonet** [comment]
Pour l'instant, à l'arrivée sur la page ou a un niveau de zoom donné, nous chargeons un rectangle de cellule plus large que ce qui est visible. Lorsque l'on se déplace dans la carte, il n'y pas de rechargement et l'on peut donc arriver au bout du rectangle chargé.
C'est une des prochaines corrections importantes à faire. Pour l'instant la seul solution est de double clique ou zoomer au bord de la carte pour recharger la bonne parcelle de données.
