### ISSUE TITLE
échec d'un chargement d'image (depuis poste mairie)

### ISSUE THREAD

**Issue by EliCommins** [davidonet/Textopoly#91]
la case reste marquée comme occupée par la suite

**Comment by davidonet** [comment]
Non confirmé depuis mon bureau
J'ai pu poster une image et la voir apparaître 

L'image apparaît elle au rechargement ? 
Je ne la vois pas. 

Qu'elle sa taille ? Il y a peut être une limite en 
upload sur le proxy mairie

**Comment by EliCommins** [comment]
8 ko

2012/10/11 David Olivari notifications@github.com

**Comment by EliCommins** [comment]
je viens de reproduire le problème
coordonnées -11, -38
le billet est enregistré, mais je ne vois pas l'image s'afficher

2012/10/11 Eli Commins eli.commins@gmail.com

**Comment by davidonet** [comment]
A tester de la mairie

**Comment by EliCommins** [comment]
Echec d'un nouveau test avec une JPEG de 6,16 Ko depuis la Mairie.

**Comment by davidonet** [comment]
Je viens de regarder les traces. Le fichier n'arrive pas jusqu'au serveur...
Il faudra que j'investigue à partir d'une connexion mairie.

**Comment by EliCommins** [comment]
ok. ce problème est secondaire pour l'instant, si ça n'arrive que dans la
config Mairie (cela dit, j'ai pu uploader cette même image sur mon compte
Facebook, par ex.)

2012/10/16 David Olivari notifications@github.com
